{
 "title": "API stats",
 "tags": [ "WSGI" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "api", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (increase(http_requests_total{job=~\"$api\"}[2m])) /2",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_created{job=~\"$api\",status!=\"2xx\"}[2m])) / 2",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(http_requests_total{job=~\"$api\"}[2m])) /2",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=~\"$api\"}[2m])\n/\nrate(http_request_duration_seconds_count{job=~\"$api\"}[2m])",
     "legendFormat": "{{ handler }}:{{ method }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$api\"}[2m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$api\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{job=~\"$api\",le=\"0.1\"}[2m]) \n/ ignoring (le) increase(http_request_duration_seconds_count{job=~\"$api\"}[2m])",
     "legendFormat": "{{ handler }}:{{ method }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{job=~\"$api\"}[2m]))",
     "legendFormat": "{{ handler }}:{{ method }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=~\"$api\"}[2m]))",
     "legendFormat": "{{ handler }}:{{ method }}"
    }
   ]
  }
 ]
}